name: Auto Commit

on:
  push:
    branches:
      - main # Trigger when changes are pushed to the 'main' branch
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight (UTC)

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # Fetch the latest code from the repository

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]" # Set the bot's name for commits
          git config user.email "github-actions[bot]@users.noreply.github.com" # Use GitHub-provided bot email

      - name: Commit Changes
        run: |
          git add . # Stage all changes
          git commit -m "Automated commit: $(date '+%Y-%m-%d %H:%M:%S')" # Add a timestamp to the commit message
          git push origin main || echo "No changes to commit" # Push changes or skip if no changes
